name: CI / Build docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn
    - name: Run linter
      run: yarn lint
    - name: Run unit tests
      run: yarn test

  build-demo:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/stephane-lieumont/ctp-webappstories

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        build-args: |
          "PUBLIC_URL=https://stephane-lieumont.fr/demo/casetespotes-webapp"
          "DEMO=true"
        push: true
        tags: ghcr.io/stephane-lieumont/ctp-webappstories:demo
        labels: ${{ steps.meta.outputs.labels }}
  
  build-production:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    
     
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/stephane-lieumont/ctp-webappstories

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        build-args: |
          "PUBLIC_URL=https://stephane-lieumont.fr/demo/casetespotes-webapp"
        push: true
        tags: ghcr.io/stephane-lieumont/ctp-webappstories:latest
        labels: ${{ steps.meta.outputs.labels }}
  
    
  
